server:
  port: 1111

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 1000
    renewal-percent-threshold: 0.85
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
